apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization




resources:
- ingress.yaml
- app/manifests/deployment.yaml
- app/manifests/service.yaml
- app/manifests/configmap.yaml
- log/manifests/deployment.yaml
- log/manifests/service.yaml
- log/manifests/configmap.yaml
- db/deployment.yaml

images:
- name: PING/APP
  newName: mluukkai/ping-pong
  newTag: b39df2e09244458e67c91842427c679605c6a24c
- name: PING/LOG
  newName: mluukkai/log-output
  newTag: b39df2e09244458e67c91842427c679605c6a24c
