apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: mluukkai/ping-pong:27
          env:
            - name: CONNECT_STRING
              valueFrom:
                configMapKeyRef:
                  name: ping-pong-conf
                  key: CONNECT_STRING
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
            initialDelaySeconds: 1
            periodSeconds: 3
          imagePullPolicy: Always
