name: Deploy application

on:
  push:
    branches:
      - main

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish app
        run: |-
          docker build --tag "mluukkai/ping-pong:$GITHUB_SHA" app
          docker push "mluukkai/ping-pong:$GITHUB_SHA"

      - name: Build and publish log
        run: |-
          docker build --tag "mluukkai/log-output:$GITHUB_SHA" log
          docker push "mluukkai/log-output:$GITHUB_SHA"